In [87]:
import requests
import json
from bs4 import BeautifulSoup as bs
import pandas as pd
import re
import numpy as np

In [12]:
SEARCH_TERM=''


#Get top shoe IDs
url = 'https://2fwotdvm2o-dsn.algolia.net/1/indexes/product_variants_v2/query?x-algolia-agent=Algolia for vanilla JavaScript 3.25.1&x-algolia-application-id=2FWOTDVM2O&x-algolia-api-key=ac96de6fef0e02bb95d433d8d5c7038a'
data = {'distinct':'true', 'hitsPerPage':'50','page':'0', 'query': SEARCH_TERM}
r = requests.post(url, data=json.dumps(data))
shoeList = pd.DataFrame.from_records(r.json()['hits'])
shoeList = shoeList[['product_template_id', 'name', 'main_picture_url']]
shoeList.rename(columns={'product_template_id': 'id', 'main_picture_url': 'picture'}, inplace=True)
shoeList

,id,name,picture
0,618984,Air Jordan 1 Retro High co.JP 'Midnight Navy' ...,https://image.goat.com/750/attachments/product...
1,567948,Air Jordan 1 Retro High OG 'Dark Mocha',https://image.goat.com/750/attachments/product...
2,566994,Air Jordan 11 Retro '25th Anniversary',https://image.goat.com/750/attachments/product...
3,618610,Air Jordan 5 Retro SE 'What The',https://image.goat.com/750/attachments/product...
4,482560,Air Jordan 1 Retro High OG 'Obsidian',https://image.goat.com/750/attachments/product...
5,664450,Sacai x VaporWaffle 'Black White',https://image.goat.com/750/attachments/product...
6,662236,Off-White x Air Jordan 5 SP 'Sail',https://image.goat.com/750/attachments/product...
7,519961,Air Jordan 1 Retro High OG 'Royal Toe',https://image.goat.com/750/attachments/product...
8,665227,Dunk Low SP Retro 'Ceramic' 2020,https://image.goat.com/750/attachments/product...
9,612313,Air Jordan 4 Retro OG 'Fire Red' 2020,https://image.goat.com/750/attachments/product...
10,676742,Sacai x VaporWaffle 'Sail',https://image.goat.com/750/attachments/product...
11,404758,Air Jordan 1 Retro High OG 'Turbo Green',https://image.goat.com/750/attachments/product...
12,665226,Dunk Low SP Retro 'Veneer' 2020,https://image.goat.com/750/attachments/product...
13,576959,Air Jordan 1 Mid 'Chicago Black Toe',https://image.goat.com/750/attachments/product...
14,693045,Yeezy 700 V3 'Safflower',https://image.goat.com/750/attachments/product...
15,603678,Off-White x Wmns Air Jordan 4 SP 'Sail',https://image.goat.com/750/attachments/product...
16,698772,Yeezy Boost 350 V2 'Fade',https://image.goat.com/750/attachments/product...
17,517360,Air Jordan 1 Retro High OG 'Court Purple 2.0',https://image.goat.com/750/attachments/product...
18,644620,Yeezy Boost 380 'Calcite Glow',https://image.goat.com/750/attachments/product...
19,697297,Air Jordan 1 Retro High co.JP GS 'Midnight Nav...,https://image.goat.com/750/attachments/product...
20,631937,Yeezy Boost 350 V2 'Carbon',https://image.goat.com/750/attachments/product...
21,697103,Air Jordan 1 Retro High OG GS 'Dark Mocha',https://image.goat.com/750/attachments/product...
22,695076,Balenciaga Track Sneaker 'Black',https://image.goat.com/750/attachments/product...
23,693245,Air Jordan 1 Mid 'Banned',https://image.goat.com/750/attachments/product...
24,461782,Air Jordan 4 Retro OG 'Bred' 2019,https://image.goat.com/750/attachments/product...
25,478948,Air Jordan 11 Retro 'Bred' 2019,https://image.goat.com/750/attachments/product...
26,538383,Air Jordan 1 Retro High 'Tokyo Bio Hack',https://image.goat.com/750/attachments/product...
27,549111,Air Jordan 1 Retro High OG 'Smoke Grey',https://image.goat.com/750/attachments/product...
28,508079,Air Jordan 1 Retro High OG 'Bloodline',https://image.goat.com/750/attachments/product...
29,485842,Air Jordan 1 Retro High OG 'Crimson Tint',https://image.goat.com/750/attachments/product...
30,704162,Cactus Plant Flea Market x Swarovski x Dunk Lo...,https://image.goat.com/750/attachments/product...
31,612859,Air Jordan 12 Retro 'Dark Concord',https://image.goat.com/750/attachments/product...
32,704152,Pharrell x NMD Human Race 'Black',https://image.goat.com/750/attachments/product...
33,105568,Yeezy Boost 350 V2 'Zebra',https://image.goat.com/750/attachments/product...
34,496584,Air Jordan 1 Retro High OG 'Pine Green 2.0',https://image.goat.com/750/attachments/product...
35,695234,Air Max 90 'Infrared' 2020,https://image.goat.com/750/attachments/product...
36,529535,Air Jordan 4 Retro 'Black Cat' 2020,https://image.goat.com/750/attachments/product...
37,695243,Yeezy Boost 350 V2 'Natural',https://image.goat.com/750/attachments/product...
38,479026,Air Jordan 1 Retro High OG 'Shattered Backboar...,https://image.goat.com/750/attachments/product...
39,568627,Wmns Air Jordan 1 Retro High OG 'Lucky Green',https://image.goat.com/750/attachments/product...
40,664578,Union LA x Air Jordan 4 Retro 'Off Noir',https://image.goat.com/750/attachments/product...
41,488879,Travis Scott x Air Jordan 1 Retro High OG 'Mocha',https://image.goat.com/750/attachments/product...
42,240,Air Force 1 '07 'White',https://image.goat.com/750/attachments/product...
43,464372,Air Jordan 6 Retro 'Infrared' 2019,https://image.goat.com/750/attachments/product...
44,411930,Wmns Air Jordan 1 Retro High OG 'Blue Chill',https://image.goat.com/750/attachments/product...
45,693044,Dunk Low Pro SB 'Atmos Elephant',https://image.goat.com/750/attachments/product...
46,553685,Air Jordan 4 Retro 'Purple Metallic',https://image.goat.com/750/attachments/product...
47,696780,Concepts x Dunk High Pro SB ‘TurDUNKen,https://image.goat.com/750/attachments/product...
48,547548,Off-White x Air Rubber Dunk 'Green Strike',https://image.goat.com/750/attachments/product...
49,116662,Yeezy Boost 350 V2 'Cream White / Triple White',https://image.goat.com/750/attachments/product...

In [116]:
shoeDict = {}
for _, shoe in shoeList.iterrows():
    print('Processing', shoe['name'])
    #Get shoe info
    url = 'https://www.goat.com/web-api/v1/product_variants'
    param = {'productTemplateId':shoe['id']} 
    header = {'User-Agent': 'Mozilla/5.0'}
    req = requests.get(url, headers=header, params=param)
    jsonInfo = req.json()
    #Turn to dataframe and clean up
    s = pd.DataFrame.from_records(jsonInfo)
    s.drop(['sizeOption', 'lowestPriceCentsByWarehouse', 'instantShipLowestPriceCents'], axis=1, inplace=True)
    s.rename(columns={'lowestPriceCents': 'price'}, inplace=True)
    s['price'] = [re.findall('(\d+)00', str(x))[0] for x in s['price']]
    s['price'] = s['price'].astype(int)
    shoeDict[shoe['name']] = s

Processing Air Jordan 1 Retro High co.JP 'Midnight Navy' 2020
Processing Air Jordan 1 Retro High OG 'Dark Mocha'
Processing Air Jordan 11 Retro '25th Anniversary'
Processing Air Jordan 5 Retro SE 'What The'
Processing Air Jordan 1 Retro High OG 'Obsidian'
Processing Sacai x VaporWaffle 'Black White'
Processing Off-White x Air Jordan 5 SP 'Sail'
Processing Air Jordan 1 Retro High OG 'Royal Toe'
Processing Dunk Low SP Retro 'Ceramic' 2020
Processing Air Jordan 4 Retro OG 'Fire Red' 2020
Processing Sacai x VaporWaffle 'Sail'
Processing Air Jordan 1 Retro High OG 'Turbo Green'
Processing Dunk Low SP Retro 'Veneer' 2020
Processing Air Jordan 1 Mid 'Chicago Black Toe'
Processing Yeezy 700 V3 'Safflower'
Processing Off-White x Wmns Air Jordan 4 SP 'Sail'
Processing Yeezy Boost 350 V2 'Fade'
Processing Air Jordan 1 Retro High OG 'Court Purple 2.0'
Processing Yeezy Boost 380 'Calcite Glow'
Processing Air Jordan 1 Retro High co.JP GS 'Midnight Navy' 2020
Processing Yeezy Boost 350 V2 'Carbon'
Processing Air Jordan 1 Retro High OG GS 'Dark Mocha'
Processing Balenciaga Track Sneaker 'Black'
Processing Air Jordan 1 Mid 'Banned'
Processing Air Jordan 4 Retro OG 'Bred' 2019
Processing Air Jordan 11 Retro 'Bred' 2019
Processing Air Jordan 1 Retro High 'Tokyo Bio Hack'
Processing Air Jordan 1 Retro High OG 'Smoke Grey'
Processing Air Jordan 1 Retro High OG 'Bloodline'
Processing Air Jordan 1 Retro High OG 'Crimson Tint'
Processing Cactus Plant Flea Market x Swarovski x Dunk Low 'Pure Platinum'
Processing Air Jordan 12 Retro 'Dark Concord'
Processing Pharrell x NMD Human Race 'Black'
Processing Yeezy Boost 350 V2 'Zebra'
Processing Air Jordan 1 Retro High OG 'Pine Green 2.0'
Processing Air Max 90 'Infrared' 2020
Processing Air Jordan 4 Retro 'Black Cat' 2020
Processing Yeezy Boost 350 V2 'Natural'
Processing Air Jordan 1 Retro High OG 'Shattered Backboard 3.0'
Processing Wmns Air Jordan 1 Retro High OG 'Lucky Green'
Processing Union LA x Air Jordan 4 Retro 'Off Noir'
Processing Travis Scott x Air Jordan 1 Retro High OG 'Mocha'
Processing Air Force 1 '07 'White'
Processing Air Jordan 6 Retro 'Infrared' 2019
Processing Wmns Air Jordan 1 Retro High OG 'Blue Chill'
Processing Dunk Low Pro SB 'Atmos Elephant'
Processing Air Jordan 4 Retro 'Purple Metallic'
Processing Concepts x Dunk High Pro SB ‘TurDUNKen
Processing Off-White x Air Rubber Dunk 'Green Strike'
Processing Yeezy Boost 350 V2 'Cream White / Triple White'

In [4]:
for name, df in shoeDict.items():
    print(name)
    p = df[(df.shoeCondition != 'new_no_defects')]
    display(p)

Air Jordan 1 Retro High co.JP 'Midnight Navy' 2020

    size     shoeCondition    boxCondition price
11   8.0  new_with_defects  good_condition   300
17   9.5  new_with_defects  good_condition   259
23  10.5  new_with_defects  good_condition   280
26  11.0  new_with_defects  good_condition   265
29  12.0  new_with_defects  good_condition   258
34  13.0  new_with_defects  good_condition   258
35  14.0  new_with_defects   badly_damaged   235
37  14.0  new_with_defects  good_condition   241
39  15.0  new_with_defects  good_condition   270

Air Jordan 1 Retro High OG 'Dark Mocha'

    size     shoeCondition     boxCondition price
14   9.0  new_with_defects   good_condition   380
19   9.5  new_with_defects  no_original_box   627
20   9.5  new_with_defects   good_condition   380
25  10.5  new_with_defects   good_condition   362
26  10.5  new_with_defects    badly_damaged   400
27  10.5              used   good_condition   345
29  11.0  new_with_defects    badly_damaged   370
31  11.0              used   good_condition   376
35  11.5  new_with_defects   good_condition   500
38  12.0  new_with_defects   good_condition   757

Air Jordan 11 Retro '25th Anniversary'

    size     shoeCondition    boxCondition price
3    8.0  new_with_defects  good_condition   300
10   9.5  new_with_defects  good_condition   299
13  10.0  new_with_defects  good_condition   305
20  12.0  new_with_defects  good_condition   350

Air Jordan 5 Retro SE 'What The'

    size     shoeCondition    boxCondition price
8    6.0  new_with_defects   badly_damaged   275
10   6.0  new_with_defects  good_condition   435
13   7.0  new_with_defects   badly_damaged   352
15   7.5  new_with_defects  good_condition   260
17   8.5              used  good_condition   210
19   8.5  new_with_defects  good_condition   279
23   9.0  new_with_defects  good_condition   281
27   9.5              used  good_condition   282
29   9.5  new_with_defects  good_condition   269
33  10.0  new_with_defects  good_condition   261
38  11.0  new_with_defects  good_condition   290
41  11.5  new_with_defects  good_condition   265
44  12.0  new_with_defects  good_condition   334
49  13.0  new_with_defects  good_condition   285
53  14.0  new_with_defects  good_condition   269

Air Jordan 1 Retro High OG 'Obsidian'

    size     shoeCondition     boxCondition price
1    7.0  new_with_defects    badly_damaged   650
4    7.0              used    badly_damaged   560
8    8.0              used   good_condition   449
9    8.0  new_with_defects   good_condition   520
12   8.5              used  no_original_box   360
13   8.5  new_with_defects   good_condition   490
15   8.5              used   good_condition   425
16   9.0              used    badly_damaged   399
17   9.0  new_with_defects   good_condition   438
19   9.0              used  no_original_box   477
21   9.0              used   good_condition   393
22   9.5              used  no_original_box   390
24   9.5  new_with_defects   good_condition  1997
27   9.5              used   good_condition   399
28  10.0              used   good_condition   350
30  10.0              used  no_original_box   340
31  10.0              used      missing_lid   450
33  10.0              used    badly_damaged   400
35  10.5              used   good_condition   382
36  10.5              used    badly_damaged   415
37  10.5              used  no_original_box   380
39  10.5  new_with_defects    badly_damaged   447
40  11.0              used   good_condition   339
42  11.0  new_with_defects   good_condition   447
44  11.0              used    badly_damaged   390
45  11.0              used  no_original_box   330
48  11.5              used   good_condition   365
49  11.5              used  no_original_box   340
51  12.0              used   good_condition   350
52  12.0  new_with_defects   good_condition   462
54  12.0              used    badly_damaged   450
55  12.0              used  no_original_box   304
56  12.5              used  no_original_box   375
58  12.5              used   good_condition   320
59  12.5  new_with_defects   good_condition   585
60  13.0              used   good_condition   350
62  13.0              used      missing_lid   360
63  13.0              used    badly_damaged   395
66  14.0  new_with_defects   good_condition   420
68  14.0              used   good_condition   325
70  15.0              used   good_condition   320
75  18.0  new_with_defects   good_condition   220

Sacai x VaporWaffle 'Black White'

    size     shoeCondition    boxCondition price
19   9.5  new_with_defects  good_condition   475

Off-White x Air Jordan 5 SP 'Sail'

    size     shoeCondition     boxCondition price
17   8.5  new_with_defects   good_condition   605
19   9.0  new_with_defects   good_condition   650
22   9.5              used   good_condition   705
25  10.0              used  no_original_box   910
28  10.5  new_with_defects    badly_damaged  1500
30  10.5  new_with_defects   good_condition   660
33  11.0              used   good_condition   600
34  11.0  new_with_defects   good_condition   655
35  11.5              used   good_condition   650
38  12.0              used   good_condition   619
41  12.0  new_with_defects    badly_damaged  1200
42  12.5              used    badly_damaged   590
48  13.0  new_with_defects   good_condition   595

Air Jordan 1 Retro High OG 'Royal Toe'

    size     shoeCondition     boxCondition price
5    5.5              used   good_condition   400
8    6.5              used   good_condition   545
10   7.0  new_with_defects   good_condition   392
12   7.5  new_with_defects   good_condition   357
13   7.5              used   good_condition   315
14   8.0              used   good_condition   283
15   8.0  new_with_defects   good_condition   333
17   8.0              used    badly_damaged   345
19   8.0              used      missing_lid   300
22   8.5              used  no_original_box   280
25   8.5              used   good_condition   289
26   9.0              used   good_condition   300
31   9.0  new_with_defects  no_original_box   375
34   9.5              used   good_condition   300
37   9.5  new_with_defects   good_condition   350
38   9.5              used  no_original_box   380
39   9.5  new_with_defects  no_original_box   300
41  10.0  new_with_defects   good_condition   340
42  10.0              used   good_condition   265
43  10.0              used  no_original_box   282
44  10.0              used    badly_damaged   264
46  10.0  new_with_defects    badly_damaged   305
48  10.5              used   good_condition   260
50  10.5              used  no_original_box   267
51  10.5  new_with_defects   good_condition   380
52  10.5              used    badly_damaged   326
53  11.0              used   good_condition   285
56  11.0              used  no_original_box   290
57  11.0              used      missing_lid   277
59  11.5              used   good_condition   245
63  11.5              used  no_original_box   343
66  12.0              used  no_original_box   258
67  12.0              used   good_condition   259
68  12.0  new_with_defects   good_condition   325
70  12.5  new_with_defects   good_condition   350
72  13.0              used   good_condition   260
74  13.0              used  no_original_box   250
77  14.0              used   good_condition   270
78  14.0  new_with_defects   good_condition   282

Dunk Low SP Retro 'Ceramic' 2020

    size     shoeCondition    boxCondition price
15  10.0  new_with_defects  good_condition   248
17  10.5  new_with_defects  good_condition   268
20  12.0  new_with_defects   badly_damaged   325

Air Jordan 4 Retro OG 'Fire Red' 2020

    size     shoeCondition    boxCondition price
4    7.5  new_with_defects   badly_damaged   310
6    7.5  new_with_defects  good_condition   251
8    8.0  new_with_defects  good_condition   270
10   8.5              used  good_condition   265
14   9.0  new_with_defects   badly_damaged   298
16   9.5  new_with_defects  good_condition   270
18  10.0  new_with_defects  good_condition   255
19  10.0              used  good_condition   260
24  10.5  new_with_defects  good_condition   270
26  11.0  new_with_defects  good_condition   260
27  11.5              used  good_condition   260
29  11.5  new_with_defects  good_condition   260
31  12.0              used  good_condition   265
32  12.0  new_with_defects  good_condition   240
36  13.0  new_with_defects  good_condition   250
41  16.0  new_with_defects  good_condition   374

Sacai x VaporWaffle 'Sail'

    size     shoeCondition    boxCondition price
22  10.5  new_with_defects  good_condition   445

Air Jordan 1 Retro High OG 'Turbo Green'

    size     shoeCondition     boxCondition price
4    7.5              used   good_condition   660
5    7.5  new_with_defects   good_condition   663
6    8.0              used   good_condition   470
7    8.0              used  no_original_box   290
12   8.5              used   good_condition   390
13   8.5  new_with_defects   good_condition   730
14   8.5              used  no_original_box   389
15   8.5              used    badly_damaged   450
17   9.0              used   good_condition   340
18   9.0              used  no_original_box   295
19   9.0              used    badly_damaged   495
22   9.5              used   good_condition   323
23   9.5              used    badly_damaged   420
24   9.5              used  no_original_box   315
25   9.5  new_with_defects   good_condition   490
26  10.0              used   good_condition   300
28  10.0              used    badly_damaged   338
29  10.0              used  no_original_box   315
31  10.5              used   good_condition   300
32  10.5              used    badly_damaged   359
33  10.5              used  no_original_box   340
35  11.0              used   good_condition   293
38  11.0              used  no_original_box   300
39  11.0              used    badly_damaged   375
41  11.5  new_with_defects   good_condition   562
42  11.5              used    badly_damaged   320
43  11.5              used  no_original_box   270
44  11.5              used   good_condition   335
47  12.0  new_with_defects   good_condition   490
48  12.0              used  no_original_box   295
49  12.0              used   good_condition   345
50  12.0              used      missing_lid   418
53  12.5              used   good_condition   375
55  13.0              used    badly_damaged   300
56  13.0              used  no_original_box   300
57  13.0  new_with_defects   good_condition   505
58  13.0              used   good_condition   325
60  14.0              used   good_condition   310
63  15.0              used  no_original_box   330
67  15.0              used   good_condition   345
72  16.0              used  no_original_box   225

Dunk Low SP Retro 'Veneer' 2020

    size     shoeCondition    boxCondition price
3    5.5  new_with_defects  good_condition   265
10   7.0  new_with_defects  good_condition   475
14   8.5  new_with_defects  good_condition   245
18   9.5  new_with_defects  good_condition   255
23  10.5  new_with_defects  good_condition   330
25  11.0  new_with_defects  good_condition   260
30  12.0  new_with_defects  good_condition   250

Air Jordan 1 Mid 'Chicago Black Toe'

    size     shoeCondition     boxCondition price
3    6.5              used   good_condition   180
6    7.0  new_with_defects    badly_damaged   270
14   8.5              used   good_condition   175
15   8.5              used  no_original_box   160
18   9.0              used    badly_damaged   155
20   9.0              used   good_condition   165
23   9.5              used    badly_damaged   175
24   9.5              used   good_condition   160
27  10.0  new_with_defects   good_condition   179
28  10.0              used   good_condition   190
31  10.5              used   good_condition   171
32  10.5              used  no_original_box   190
38  11.5              used   good_condition   165
40  12.0              used   good_condition   179
41  12.0              used    badly_damaged   166
46  13.0              used   good_condition   145
51  17.0  new_with_defects    badly_damaged   214

Yeezy 700 V3 'Safflower'

    size     shoeCondition    boxCondition price
10   8.0  new_with_defects  good_condition   250

Off-White x Wmns Air Jordan 4 SP 'Sail'

    size     shoeCondition     boxCondition price
2    5.5              used   good_condition   960
4    6.0              used   good_condition  1000
6    6.0  new_with_defects   good_condition   945
8    6.5              used   good_condition   760
11   7.0              used   good_condition  1200
13   7.0  new_with_defects   good_condition  1400
15   7.5  new_with_defects    badly_damaged  1418
16   7.5  new_with_defects   good_condition  1240
19   8.0  new_with_defects   good_condition   948
21   8.5  new_with_defects   good_condition   975
22   8.5  new_with_defects    badly_damaged  1030
23   8.5              used    badly_damaged  1060
24   8.5              used   good_condition   900
26   9.0              used      missing_lid   750
27   9.0  new_with_defects   good_condition  1020
28   9.0              used   good_condition   950
31   9.5              used   good_condition   900
32   9.5  new_with_defects    badly_damaged  1001
33   9.5  new_with_defects   good_condition   950
36  10.0  new_with_defects   good_condition  1090
37  10.0  new_with_defects    badly_damaged  1143
38  10.0              used    badly_damaged  1056
39  10.0              used   good_condition  1056
41  10.5  new_with_defects   good_condition  1145
42  10.5              used   good_condition  1000
45  10.5              used    badly_damaged   978
46  10.5  new_with_defects  no_original_box  1100
49  11.0              used   good_condition  1025
50  11.0  new_with_defects   good_condition  1144
51  11.5  new_with_defects   good_condition  1365
53  11.5              used   good_condition  1500
55  12.0              used   good_condition  1361
56  12.0  new_with_defects   good_condition  1600
58  12.5              used   good_condition  1400
60  12.5  new_with_defects   good_condition  2440
61  12.5  new_with_defects    badly_damaged  2150
64  13.0              used   good_condition  1600
65  13.0              used  no_original_box  1615
68  13.5              used   good_condition  1890
70  13.5  new_with_defects    badly_damaged  2320
73  14.5  new_with_defects   good_condition  2674

Yeezy Boost 350 V2 'Fade'

Empty DataFrame
Columns: [size, shoeCondition, boxCondition, price]
Index: []

Air Jordan 1 Retro High OG 'Court Purple 2.0'

    size     shoeCondition     boxCondition price
4    5.5  new_with_defects   good_condition   600
6    6.0              used  no_original_box   420
7    6.0              used   good_condition   401
11   7.5              used   good_condition   295
12   7.5  new_with_defects   good_condition   380
14   8.0  new_with_defects   good_condition   320
16   8.0              used   good_condition   310
17   8.5              used   good_condition   275
18   8.5              used    badly_damaged   300
21   9.0  new_with_defects   good_condition   469
23   9.0              used   good_condition   270
25   9.0  new_with_defects    badly_damaged   353
27   9.5              used   good_condition   270
28   9.5  new_with_defects   good_condition   298
31  10.0              used   good_condition   280
32  10.0  new_with_defects   good_condition   290
34  10.0  new_with_defects      missing_lid   450
36  10.0              used  no_original_box   300
40  10.5              used  no_original_box   280
41  10.5  new_with_defects   good_condition   315
42  10.5              used   good_condition   268
44  11.0              used   good_condition   275
46  11.0  new_with_defects   good_condition   305
47  11.0              used  no_original_box   285
48  11.0  new_with_defects  no_original_box   275
49  11.0  new_with_defects    badly_damaged   309
51  11.5  new_with_defects    badly_damaged   722
52  11.5              used  no_original_box   285
54  11.5              used   good_condition   300
56  12.0              used   good_condition   280
57  12.0  new_with_defects   good_condition   324
60  12.5              used  no_original_box   277
62  12.5              used   good_condition   271
63  13.0              used  no_original_box   300
65  13.0              used   good_condition   275
66  13.0              used    badly_damaged   350
70  14.0              used   good_condition   300
75  18.0  new_with_defects   good_condition   190

Yeezy Boost 380 'Calcite Glow'

    size     shoeCondition    boxCondition price
5    6.0  new_with_defects  good_condition   243
9    7.5  new_with_defects   badly_damaged   257
14   8.5  new_with_defects  good_condition   243
20  10.5  new_with_defects  good_condition   253
25  11.0  new_with_defects  good_condition   280
27  11.5  new_with_defects  good_condition   300
29  12.0              used  good_condition   260
31  12.0  new_with_defects  good_condition   237
33  12.5  new_with_defects  good_condition   300
35  13.0              used  good_condition   230
36  13.0  new_with_defects  good_condition   264

Air Jordan 1 Retro High co.JP GS 'Midnight Navy' 2020

    size     shoeCondition    boxCondition price
14   5.5  new_with_defects  good_condition   238
17   6.0              used  good_condition   400
18   6.0  new_with_defects  good_condition   230
22   7.0  new_with_defects  good_condition   249

Yeezy Boost 350 V2 'Carbon'

    size     shoeCondition     boxCondition price
2    4.0              used   good_condition   320
3    4.0  new_with_defects   good_condition   295
6    4.5              used  no_original_box   279
9    4.5  new_with_defects   good_condition   298
12   5.0              used   good_condition   285
19   6.5              used   good_condition   400
21   7.0  new_with_defects    badly_damaged   298
23   7.0              used  no_original_box   360
25   7.5  new_with_defects    badly_damaged   300
26   7.5              used   good_condition   275
29   8.0              used   good_condition   255
32   8.0  new_with_defects   good_condition   270
35   8.5              used   good_condition   245
36   8.5  new_with_defects   good_condition   295
40   9.0              used   good_condition   238
44   9.5              used   good_condition   250
47  10.0              used   good_condition   240
48  10.0  new_with_defects   good_condition   298
52  10.5              used   good_condition   237
54  10.5              used  no_original_box   230
55  10.5  new_with_defects   good_condition   262
59  11.0              used   good_condition   235
60  11.0  new_with_defects   good_condition   295
64  11.5              used   good_condition   282
66  12.0  new_with_defects   good_condition   272
67  12.0              used   good_condition   250
72  13.0              used   good_condition   270
75  13.5              used   good_condition   316
78  14.0  new_with_defects   good_condition   285

Air Jordan 1 Retro High OG GS 'Dark Mocha'

    size     shoeCondition    boxCondition price
7    5.0  new_with_defects  good_condition   330
9    5.5  new_with_defects  good_condition   370
13   6.0  new_with_defects  good_condition   390
15   6.5  new_with_defects   badly_damaged   360
19   7.0              used  good_condition   340

Balenciaga Track Sneaker 'Black'

Empty DataFrame
Columns: [size, shoeCondition, boxCondition, price]
Index: []

Air Jordan 1 Mid 'Banned'

    size     shoeCondition    boxCondition price
10  10.0  new_with_defects   badly_damaged   220
15  11.0  new_with_defects  good_condition   155

Air Jordan 4 Retro OG 'Bred' 2019

    size     shoeCondition     boxCondition price
10   7.0              used   good_condition   380
12   7.5  new_with_defects   good_condition   380
13   7.5              used  no_original_box   355
15   7.5              used   good_condition   340
17   8.0              used   good_condition   258
18   8.0              used  no_original_box   310
19   8.0              used    badly_damaged   310
20   8.0  new_with_defects   good_condition   429
22   8.5              used  no_original_box   220
23   8.5              used   good_condition   280
25   8.5  new_with_defects   good_condition   395
26   8.5              used      missing_lid   332
27   8.5  new_with_defects    badly_damaged   400
28   8.5              used    badly_damaged   293
29   9.0              used   good_condition   275
31   9.0              used  no_original_box   255
32   9.0              used    badly_damaged   260
33   9.0  new_with_defects   good_condition   588
35   9.5              used   good_condition   300
36   9.5              used  no_original_box   286
39  10.0              used  no_original_box   230
41  10.0              used   good_condition   300
42  10.0              used      missing_lid   400
44  10.0  new_with_defects   good_condition   424
47  10.5              used   good_condition   300
48  10.5  new_with_defects   good_condition   470
49  10.5              used    badly_damaged   325
50  10.5              used  no_original_box   250
51  10.5              used      missing_lid   420
54  11.0              used   good_condition   310
55  11.0              used  no_original_box   301
56  11.0  new_with_defects   good_condition   559
58  11.0              used    badly_damaged   185
59  11.5              used  no_original_box   306
61  11.5              used   good_condition   280
62  11.5              used    badly_damaged   355
66  12.0              used   good_condition   343
67  12.0              used    badly_damaged   221
68  12.0              used  no_original_box   300
69  12.5              used   good_condition   338
71  12.5              used  no_original_box   420
72  13.0              used   good_condition   310
73  13.0              used  no_original_box   273
76  13.0              used    badly_damaged   395
77  14.0              used   good_condition   309
78  14.0              used    badly_damaged   399
80  14.0              used  no_original_box   282
83  15.0              used   good_condition   425
84  15.0  new_with_defects  no_original_box   420
85  15.0              used  no_original_box   371

Air Jordan 11 Retro 'Bred' 2019

     size     shoeCondition     boxCondition price
6     5.0  new_with_defects   good_condition   454
10    6.0              used   good_condition   400
13    7.0  new_with_defects    badly_damaged   450
15    7.5              used   good_condition   270
20    8.0  new_with_defects   good_condition   375
21    8.0              used   good_condition   260
22    8.0  new_with_defects    badly_damaged   315
23    8.0              used    badly_damaged   245
24    8.0              used  no_original_box   200
27    8.5  new_with_defects   good_condition   364
28    8.5              used  no_original_box   230
29    8.5  new_with_defects    badly_damaged   350
30    8.5              used    badly_damaged   273
31    8.5              used   good_condition   250
34    9.0  new_with_defects   good_condition   340
36    9.0              used    badly_damaged   243
37    9.0              used   good_condition   239
38    9.0              used  no_original_box   175
40    9.5              used  no_original_box   244
42    9.5              used    badly_damaged   300
43    9.5              used   good_condition   233
45   10.0              used   good_condition   300
46   10.0              used  no_original_box   240
47   10.0  new_with_defects    badly_damaged   400
48   10.0              used    badly_damaged   349
51   10.0  new_with_defects   good_condition   370
53   10.5              used   good_condition   240
54   10.5              used  no_original_box   255
55   10.5  new_with_defects   good_condition   365
58   10.5              used    badly_damaged   330
60   11.0              used   good_condition   300
63   11.0              used  no_original_box   284
64   11.0  new_with_defects   good_condition   390
65   11.0              used    badly_damaged   305
67   11.5  new_with_defects   good_condition   390
68   11.5              used   good_condition   250
71   11.5              used    badly_damaged   330
72   11.5              used  no_original_box   280
73   12.0              used   good_condition   285
74   12.0              used  no_original_box   266
76   12.0  new_with_defects   good_condition   349
77   12.0              used    badly_damaged   330
82   12.5              used   good_condition   249
83   12.5              used  no_original_box   271
85   13.0              used    badly_damaged   293
86   13.0              used  no_original_box   340
87   13.0              used   good_condition   282
89   13.0  new_with_defects    badly_damaged   645
91   13.0  new_with_defects   good_condition   435
92   14.0              used   good_condition   425
94   14.0              used    badly_damaged   390
95   14.0              used  no_original_box   600
97   15.0              used    badly_damaged   250
100  16.0              used   good_condition   190

Air Jordan 1 Retro High 'Tokyo Bio Hack'

    size     shoeCondition     boxCondition price
7    7.5              used   good_condition   350
9    7.5  new_with_defects    badly_damaged   360
12   8.0              used   good_condition   275
15   8.0  new_with_defects   good_condition  2000
20   9.0              used   good_condition   282
26   9.5              used    badly_damaged   340
27   9.5  new_with_defects   good_condition   295
28   9.5              used   good_condition   260
31  10.0              used   good_condition   239
32  10.0              used  no_original_box   230
34  10.5              used    badly_damaged   270
35  10.5              used   good_condition   243
36  10.5  new_with_defects   good_condition   260
39  11.0  new_with_defects   good_condition   275
40  11.0              used   good_condition   245
41  11.0              used  no_original_box   250
43  11.0  new_with_defects    badly_damaged   260
48  12.0              used   good_condition   250
49  12.0  new_with_defects    badly_damaged   325
53  13.0              used   good_condition   282

Air Jordan 1 Retro High OG 'Smoke Grey'

    size     shoeCondition     boxCondition price
4    7.5              used  no_original_box   280
6    7.5  new_with_defects   good_condition   321
8    8.0              used   good_condition   278
9    8.0  new_with_defects   good_condition   320
12   8.5              used   good_condition   230
13   8.5  new_with_defects   good_condition   340
16   9.0              used  no_original_box   255
18   9.0              used   good_condition   254
19   9.0  new_with_defects   good_condition   275
21   9.5              used   good_condition   289
24  10.0              used   good_condition   259
25  10.0  new_with_defects    badly_damaged   349
26  10.0              used    badly_damaged   260
28  10.0  new_with_defects   good_condition   285
32  10.5              used   good_condition   249
33  10.5  new_with_defects    badly_damaged   310
34  10.5  new_with_defects   good_condition   290
35  11.0  new_with_defects   good_condition   278
37  11.0              used   good_condition   260
40  11.0  new_with_defects    badly_damaged   315
43  11.5              used   good_condition   271
45  11.5              used  no_original_box   300
47  12.0              used   good_condition   245
50  12.5              used   good_condition   270
51  12.5  new_with_defects   good_condition   346
53  13.0              used  no_original_box   225
54  13.0              used   good_condition   235

Air Jordan 1 Retro High OG 'Bloodline'

    size     shoeCondition     boxCondition price
1    7.0              used   good_condition   420
3    7.5              used   good_condition   451
5    7.5  new_with_defects   good_condition   450
7    8.0  new_with_defects   good_condition   280
9    8.0              used   good_condition   280
10   8.5              used   good_condition   210
11   8.5              used    badly_damaged   250
12   8.5              used  no_original_box   215
14   8.5  new_with_defects   good_condition   320
16   9.0              used   good_condition   200
17   9.0  new_with_defects   good_condition   279
18   9.0              used  no_original_box   190
20   9.5              used  no_original_box   235
22   9.5              used   good_condition   183
24   9.5              used    badly_damaged   233
27  10.0  new_with_defects   good_condition   258
28  10.0  new_with_defects      missing_lid   294
30  10.0              used   good_condition   215
31  10.0              used  no_original_box   238
32  10.0              used    badly_damaged   165
35  10.5              used   good_condition   205
36  10.5  new_with_defects   good_condition   237
37  10.5              used  no_original_box   290
38  10.5  new_with_defects  no_original_box   256
39  10.5              used    badly_damaged   215
42  11.0              used  no_original_box   160
43  11.0              used    badly_damaged   215
44  11.0              used   good_condition   180
45  11.0  new_with_defects   good_condition   259
47  11.5              used   good_condition   200
48  11.5  new_with_defects  no_original_box   250
49  11.5              used  no_original_box   280
50  12.0              used   good_condition   190
52  12.0              used  no_original_box   185
54  12.0  new_with_defects   good_condition   237
55  12.5              used   good_condition   300
56  12.5              used  no_original_box   238
60  13.0  new_with_defects  no_original_box   225
61  13.0              used   good_condition   180
62  13.0              used  no_original_box   194

Air Jordan 1 Retro High OG 'Crimson Tint'

    size     shoeCondition     boxCondition price
1    7.5              used  no_original_box   275
2    7.5  new_with_defects   good_condition   333
4    7.5              used   good_condition   249
5    8.0              used   good_condition   290
6    8.0              used    badly_damaged   310
8    8.0  new_with_defects   good_condition   325
10   8.5  new_with_defects   good_condition   309
11   8.5  new_with_defects    badly_damaged   308
12   8.5              used  no_original_box   280
13   8.5              used   good_condition   255
15   9.0              used   good_condition   245
17   9.0  new_with_defects   good_condition   299
19   9.5              used   good_condition   250
20   9.5              used    badly_damaged   260
21   9.5              used  no_original_box   275
22  10.0              used    badly_damaged   183
24  10.0              used   good_condition   210
25  10.0              used  no_original_box   210
26  10.0  new_with_defects   good_condition   325
28  10.5              used    badly_damaged   245
29  10.5              used  no_original_box   190
31  10.5              used   good_condition   224
33  11.0  new_with_defects    badly_damaged   349
34  11.0              used    badly_damaged   200
35  11.0              used  no_original_box   190
36  11.0              used   good_condition   227
37  11.0  new_with_defects   good_condition   307
38  11.5              used  no_original_box   160
39  11.5              used   good_condition   199
41  11.5  new_with_defects    badly_damaged   333
44  12.0              used   good_condition   215
45  12.0              used  no_original_box   198
46  12.0              used    badly_damaged   250
47  12.0  new_with_defects      missing_lid   319
48  12.5              used    badly_damaged   249
51  13.0              used    badly_damaged   230
52  13.0              used  no_original_box   224
53  13.0              used   good_condition   209
55  14.0  new_with_defects    badly_damaged   315
56  14.0              used      missing_lid   194
57  14.0              used   good_condition   200
59  15.0              used  no_original_box   210
63  16.0  new_with_defects   good_condition   130

Cactus Plant Flea Market x Swarovski x Dunk Low 'Pure Platinum'

Empty DataFrame
Columns: [size, shoeCondition, boxCondition, price]
Index: []

Air Jordan 12 Retro 'Dark Concord'

    size     shoeCondition     boxCondition price
2    7.0  new_with_defects   good_condition   295
4    7.5  new_with_defects   good_condition   215
5    8.0              used   good_condition   200
7    8.0  new_with_defects   good_condition   248
9    8.5              used   good_condition   210
10   8.5  new_with_defects   good_condition   240
12   9.0  new_with_defects   good_condition   248
17  10.0              used   good_condition   220
21  11.0              used   good_condition   215
24  11.0  new_with_defects   good_condition   265
29  12.0  new_with_defects   good_condition   240
31  13.0              used  no_original_box   180
33  13.0              used    badly_damaged   227
34  13.0  new_with_defects    badly_damaged   249

Pharrell x NMD Human Race 'Black'

Empty DataFrame
Columns: [size, shoeCondition, boxCondition, price]
Index: []

Yeezy Boost 350 V2 'Zebra'

     size     shoeCondition     boxCondition price
1     4.0              used    badly_damaged   350
2     4.0              used   good_condition   290
3     4.0              used  no_original_box   285
4     4.0  new_with_defects   good_condition   480
5     4.5              used  no_original_box   373
..    ...               ...              ...   ...
106  13.5              used   good_condition   499
107  13.5              used  no_original_box   370
108  14.0              used    badly_damaged   390
110  14.0              used   good_condition   250
112  16.0              used   good_condition   300

[68 rows x 4 columns]

Air Jordan 1 Retro High OG 'Pine Green 2.0'

    size     shoeCondition     boxCondition price
0    7.0              used   good_condition   200
3    7.5              used  no_original_box   243
4    7.5              used   good_condition   285
6    8.0              used    badly_damaged   258
7    8.0              used  no_original_box   299
9    8.0  new_with_defects  no_original_box   250
10   8.0              used   good_condition   257
12   8.5              used  no_original_box   224
14   8.5              used   good_condition   244
15   8.5              used    badly_damaged   210
17   8.5  new_with_defects   good_condition   270
18   9.0  new_with_defects  no_original_box   175
20   9.0              used   good_condition   220
21   9.0              used  no_original_box   229
22   9.0  new_with_defects   good_condition   245
24   9.0  new_with_defects    badly_damaged   278
25   9.0  new_with_defects      missing_lid   270
27   9.5              used   good_condition   240
29   9.5  new_with_defects   good_condition   271
30   9.5              used  no_original_box   255
32  10.0              used      missing_lid   275
35  10.0              used   good_condition   230
36  10.0              used  no_original_box   222
37  10.5              used   good_condition   240
39  10.5              used  no_original_box   199
42  11.0  new_with_defects   good_condition   262
43  11.0              used    badly_damaged   270
46  11.0              used  no_original_box   230
47  11.0              used   good_condition   235
49  11.5              used   good_condition   245
50  12.0              used    badly_damaged   270
52  12.0              used  no_original_box   234
53  12.0              used   good_condition   255
57  13.0              used   good_condition   265
58  13.0              used    badly_damaged   250
61  14.0              used   good_condition   220
63  15.0              used  no_original_box   204
65  16.0              used    badly_damaged   245
66  16.0              used   good_condition   250
68  17.0              used   good_condition   180

Air Max 90 'Infrared' 2020

    size     shoeCondition    boxCondition price
12   8.0  new_with_defects   badly_damaged   140
13   8.0  new_with_defects  good_condition   164
15   8.5  new_with_defects  good_condition   174
19  10.0  new_with_defects  good_condition   185
23  10.5  new_with_defects  good_condition   170
27  12.0  new_with_defects  good_condition   160

Air Jordan 4 Retro 'Black Cat' 2020

    size     shoeCondition     boxCondition price
1    7.0  new_with_defects  no_original_box   450
4    7.5              used   good_condition   450
5    8.0              used   good_condition   340
7    8.0  new_with_defects   good_condition   400
9    8.0              used    badly_damaged   324
10   8.0              used  no_original_box   325
13   8.5              used  no_original_box   260
14   8.5  new_with_defects   good_condition   385
15   8.5              used   good_condition   309
16   8.5  new_with_defects  no_original_box   365
18   9.0              used    badly_damaged   310
19   9.0              used  no_original_box   290
20   9.0              used   good_condition   300
24   9.5              used    badly_damaged   345
26   9.5  new_with_defects    badly_damaged   478
27   9.5              used   good_condition   300
28   9.5              used  no_original_box   240
29  10.0              used   good_condition   300
32  10.0  new_with_defects    badly_damaged   421
34  10.0              used    badly_damaged   300
35  10.0              used  no_original_box   345
36  10.0  new_with_defects   good_condition   443
38  10.5              used    badly_damaged   300
40  10.5              used   good_condition   350
41  11.0              used    badly_damaged   360
42  11.0              used  no_original_box   279
44  11.0              used   good_condition   175
46  11.0  new_with_defects   good_condition   399
47  11.5              used    badly_damaged   359
48  11.5              used   good_condition   310
53  12.0              used    badly_damaged   420
54  12.0              used  no_original_box   200
55  12.0              used   good_condition   310
56  12.0  new_with_defects   good_condition   550
58  12.5              used    badly_damaged   400
60  13.0              used   good_condition   300
62  13.0              used    badly_damaged   330
64  13.0              used  no_original_box   260
67  14.0              used    badly_damaged   282
69  15.0              used    badly_damaged  1000
70  16.0              used  no_original_box   525

Yeezy Boost 350 V2 'Natural'

    size     shoeCondition     boxCondition price
7    6.0              used   good_condition   300
10   7.0              used   good_condition   350
13   8.0              used   good_condition   259
15   8.0  new_with_defects   good_condition   260
17   8.5  new_with_defects   good_condition   271
19   9.0              used    badly_damaged   200
22   9.5              used   good_condition   259
25  10.0  new_with_defects   good_condition   250
26  10.5              used   good_condition   290
33  11.5              used   good_condition   230
36  12.0              used   good_condition   236
38  13.0              used  no_original_box   200

Air Jordan 1 Retro High OG 'Shattered Backboard 3.0'

    size     shoeCondition     boxCondition price
4    8.0              used   good_condition   360
7    8.0              used  no_original_box   300
8    8.0  new_with_defects   good_condition   371
9    8.5              used   good_condition   325
13   8.5              used    badly_damaged   287
15   9.0  new_with_defects   good_condition   358
16   9.0              used   good_condition   300
21   9.5              used   good_condition   340
22  10.0              used   good_condition   340
24  10.0              used  no_original_box   310
26  10.5              used   good_condition   299
27  10.5              used  no_original_box   260
30  11.0  new_with_defects    badly_damaged   399
31  11.0              used   good_condition   330
32  11.0              used  no_original_box   320
35  11.0              used    badly_damaged   320
36  11.5              used   good_condition   360
40  12.0              used   good_condition   330
41  12.0              used  no_original_box   300
43  12.0              used    badly_damaged   315
45  13.0              used   good_condition   399
47  13.0              used  no_original_box   335
52  14.0              used  no_original_box   368
53  14.0              used   good_condition   300
56  15.0              used   good_condition   310

Wmns Air Jordan 1 Retro High OG 'Lucky Green'

    size     shoeCondition    boxCondition price
1    5.0  new_with_defects  good_condition   234
7    7.0              used  good_condition   499
8    7.0  new_with_defects  good_condition   240
10   7.5              used  good_condition   300
15   8.5  new_with_defects   badly_damaged   320
16   8.5  new_with_defects  good_condition   229
17   9.0              used  good_condition   251
19   9.0  new_with_defects  good_condition   270
24  10.0  new_with_defects  good_condition   280
26  10.5  new_with_defects  good_condition   600
31  12.0  new_with_defects  good_condition   265

Union LA x Air Jordan 4 Retro 'Off Noir'

    size     shoeCondition    boxCondition price
7    6.5              used  good_condition   490
11   7.5              used  good_condition   510
18   9.0              used  good_condition   740
21   9.5  new_with_defects  good_condition   790
22  10.0  new_with_defects   badly_damaged   720
24  10.0              used  good_condition   739
28  10.5              used  good_condition   856
30  11.0  new_with_defects  good_condition   686
33  11.5  new_with_defects  good_condition   950
39  13.0              used  good_condition   640

Travis Scott x Air Jordan 1 Retro High OG 'Mocha'

    size     shoeCondition     boxCondition price
8    6.5              used    badly_damaged  2699
12   7.5  new_with_defects  no_original_box  2305
17   8.0              used  no_original_box  1545
19   8.0              used    badly_damaged  1350
20   8.0              used   good_condition  1519
24   8.5              used    badly_damaged  2105
25   8.5              used   good_condition  1538
26   8.5              used  no_original_box  1400
27   8.5  new_with_defects  no_original_box  1830
29   9.0              used    badly_damaged  1344
30   9.0  new_with_defects   good_condition  2300
31   9.0              used  no_original_box  1160
33   9.0              used   good_condition  1365
35   9.5              used  no_original_box  1450
37   9.5  new_with_defects   good_condition  1800
38   9.5              used   good_condition  1111
41   9.5              used    badly_damaged  1490
42  10.0              used  no_original_box  1375
44  10.0              used   good_condition  1300
45  10.0  new_with_defects    badly_damaged  1750
47  10.0              used    badly_damaged  1774
49  10.0  new_with_defects   good_condition  1600
50  10.5              used   good_condition  1350
52  10.5              used  no_original_box  1200
54  10.5  new_with_defects   good_condition  1700
56  11.0              used   good_condition  1300
57  11.0  new_with_defects   good_condition  1670
58  11.0              used    badly_damaged  1300
61  11.5              used   good_condition  1279
64  11.5              used    badly_damaged  1500
65  11.5  new_with_defects   good_condition  1913
67  12.0              used   good_condition  1300
68  12.0              used      missing_lid  1399
70  12.0              used    badly_damaged  1000
71  12.0  new_with_defects   good_condition  1600
73  13.0              used  no_original_box  1025
74  13.0              used   good_condition  1149
75  13.0  new_with_defects   good_condition  1525
77  13.0  new_with_defects    badly_damaged  1399
78  13.0              used    badly_damaged  1166
79  13.0  new_with_defects  no_original_box  1600
83  14.0              used   good_condition  1005
85  15.0  new_with_defects   good_condition  1350

Air Force 1 '07 'White'

     size     shoeCondition     boxCondition price
3     6.0  new_with_defects   good_condition   105
6     6.5              used   good_condition   117
8     6.5              used  no_original_box    87
10    7.0              used    badly_damaged    52
11    7.0  new_with_defects   good_condition    70
..    ...               ...              ...   ...
110  13.0              used    badly_damaged    69
112  14.0              used  no_original_box    40
117  15.0              used   good_condition    50
118  15.0              used  no_original_box    70
122  17.0              used  no_original_box    90

[67 rows x 4 columns]

Air Jordan 6 Retro 'Infrared' 2019

    size     shoeCondition     boxCondition price
5    7.0              used   good_condition   245
6    7.0              used  no_original_box   200
9    7.5              used   good_condition   210
10   8.0              used    badly_damaged   225
11   8.0              used   good_condition   150
13   8.0              used  no_original_box   175
14   8.0  new_with_defects  no_original_box   284
15   8.0  new_with_defects   good_condition   280
18   8.5  new_with_defects   good_condition   290
20   8.5              used  no_original_box   230
21   8.5  new_with_defects    badly_damaged   285
22   8.5              used   good_condition   240
25   9.0              used   good_condition   190
27   9.0              used  no_original_box   150
28   9.0  new_with_defects  no_original_box   300
29   9.0  new_with_defects   good_condition   286
31   9.0              used    badly_damaged   330
33   9.5  new_with_defects   good_condition   290
34   9.5              used    badly_damaged   200
35   9.5              used  no_original_box   100
36   9.5  new_with_defects    badly_damaged   315
37   9.5              used   good_condition   180
38  10.0              used   good_condition   230
40  10.0              used    badly_damaged   190
41  10.0              used  no_original_box   161
42  10.0  new_with_defects   good_condition   270
44  10.0  new_with_defects    badly_damaged   315
46  10.5              used   good_condition   165
47  10.5              used    badly_damaged   225
50  10.5              used  no_original_box   130
51  10.5  new_with_defects   good_condition   305
53  10.5  new_with_defects    badly_damaged   325
54  10.5  new_with_defects      missing_lid   339
55  11.0              used  no_original_box   249
57  11.0  new_with_defects   good_condition   323
58  11.0              used    badly_damaged   185
59  11.0              used   good_condition   235
62  11.5              used   good_condition   260
63  11.5              used  no_original_box   240
65  12.0              used   good_condition   225
68  12.0              used  no_original_box   211
69  12.0  new_with_defects      missing_lid   350
70  12.0              used    badly_damaged   325
71  12.0  new_with_defects  no_original_box   340
72  12.0  new_with_defects   good_condition   360
74  12.5              used   good_condition   407
75  13.0              used   good_condition   215
79  14.0              used  no_original_box   282
81  14.0  new_with_defects   good_condition   400
82  14.0              used   good_condition   400
83  15.0              used    badly_damaged   300
86  15.0              used   good_condition   190
88  16.0              used      missing_lid   200
91  17.0              used      missing_lid   160

Wmns Air Jordan 1 Retro High OG 'Blue Chill'

    size     shoeCondition     boxCondition price
4    6.0              used   good_condition   700
6    6.5  new_with_defects   good_condition   615
8    7.0  new_with_defects   good_condition   580
9    7.5              used   good_condition   380
11   7.5  new_with_defects   good_condition   590
12   7.5              used    badly_damaged   385
14   8.0  new_with_defects   good_condition   555
15   8.0              used   good_condition   450
17   8.5  new_with_defects   good_condition   525
18   8.5              used   good_condition   500
19   8.5              used    badly_damaged   375
21   9.0  new_with_defects   good_condition   503
22   9.0  new_with_defects    badly_damaged   500
23   9.0              used  no_original_box   500
25   9.5              used   good_condition   400
26   9.5  new_with_defects    badly_damaged   535
27   9.5  new_with_defects   good_condition   495
30  10.0  new_with_defects   good_condition   560
31  10.0              used   good_condition   455
32  10.0              used  no_original_box   500
34  10.5              used   good_condition   555
35  10.5              used  no_original_box   505
36  10.5  new_with_defects   good_condition   588
37  11.0  new_with_defects   good_condition   600
39  11.0              used    badly_damaged   559
40  11.0              used   good_condition   535
41  11.0  new_with_defects    badly_damaged   633
43  11.5              used   good_condition   590
46  12.0  new_with_defects    badly_damaged   550
47  12.0  new_with_defects  no_original_box   520
48  12.0              used   good_condition   599
49  12.0              used  no_original_box   465

Dunk Low Pro SB 'Atmos Elephant'

    size     shoeCondition    boxCondition price
6    6.5  new_with_defects  good_condition   345
11   8.0  new_with_defects  good_condition   350
23  11.5  new_with_defects  good_condition   374

Air Jordan 4 Retro 'Purple Metallic'

    size     shoeCondition     boxCondition price
2    8.0              used   good_condition   269
3    8.0              used  no_original_box   225
6    8.5              used   good_condition   261
8    9.0  new_with_defects   good_condition   275
10   9.0              used   good_condition   235
11   9.0              used    badly_damaged   260
12   9.0              used  no_original_box   265
14   9.5              used  no_original_box   240
15   9.5              used   good_condition   275
17  10.0  new_with_defects   good_condition   250
18  10.0              used   good_condition   247
19  10.0              used  no_original_box   219
21  10.0              used    badly_damaged   260
22  10.0  new_with_defects    badly_damaged   294
23  10.5              used    badly_damaged   245
24  10.5              used   good_condition   240
26  10.5              used  no_original_box   199
29  11.0  new_with_defects    badly_damaged   350
31  11.0              used   good_condition   240
32  11.0              used  no_original_box   220
34  11.0  new_with_defects      missing_lid   325
37  11.5              used  no_original_box   210
38  11.5  new_with_defects    badly_damaged   290
39  11.5              used    badly_damaged   227
41  11.5              used   good_condition   240
42  11.5  new_with_defects   good_condition   270
44  12.0              used   good_condition   230
46  12.0              used    badly_damaged   219
47  12.0              used  no_original_box   220
48  12.0  new_with_defects  no_original_box   256
50  12.0  new_with_defects   good_condition   245
53  12.5  new_with_defects   good_condition   300
54  13.0              used  no_original_box   205
56  13.0              used    badly_damaged   205
58  13.0              used   good_condition   227
62  14.0              used    badly_damaged   225
65  15.0              used    badly_damaged   225

Concepts x Dunk High Pro SB ‘TurDUNKen

Empty DataFrame
Columns: [size, shoeCondition, boxCondition, price]
Index: []

Off-White x Air Rubber Dunk 'Green Strike'

    size     shoeCondition    boxCondition price
4    5.0  new_with_defects  good_condition   315
10   7.0              used  good_condition   320
13   7.5              used  good_condition   295
18   8.5              used  good_condition   310
25  10.0              used  good_condition   315
27  10.0  new_with_defects  good_condition   326
30  10.5              used  good_condition   382
31  10.5  new_with_defects  good_condition   304
32  11.0              used  good_condition   320
36  11.5              used  good_condition   298
41  13.0              used  good_condition   270

Yeezy Boost 350 V2 'Cream White / Triple White'

     size     shoeCondition     boxCondition price
1     4.0              used  no_original_box   270
2     4.0              used   good_condition   315
5     4.5              used   good_condition   411
6     4.5              used  no_original_box   393
7     5.0  new_with_defects   good_condition   580
..    ...               ...              ...   ...
111  14.0              used  no_original_box   225
112  14.0              used    badly_damaged   450
113  14.0              used   good_condition   285
114  14.5              used   good_condition   399
115  16.0  new_with_defects   good_condition   465

[82 rows x 4 columns]

In [18]:
availableSizes = p['size'].unique()

array([ 4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,
        9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 14. , 14.5, 16. ])

In [122]:
#take in table of prices of 1 shoe, return with price differences

#sortType 0 = used vs newNoDefect; 1 = newNoDefect vs newWithDefect; 2 = newNoDefectGoodBox vs newNoDefectBadBox
#boxCond 0 = no preference; 1 = box exists in good condition; 2 = box exists
def sizeSort(shoes, sortType, boxCond, name):
    output = dict()
    
    #used vs newNoDefect
    if sortType == 0:
        category1 = 'new_no_defects'
        category2 = 'used'
    #newNoDefect vs newWithDefect
    elif sortType == 1:
        category1 = 'new_no_defects'
        category2 = 'new_with_defects'
        
    availableSizes = shoes['size'].unique()
    for size in availableSizes:
            sizeSelect = shoes.loc[shoes['size']==size]
            if (category1 not in sizeSelect['shoeCondition'].values) or (category2 not in sizeSelect['shoeCondition'].values):
                continue
            #no preference in box
            if boxCond == 0:
                price1 = sizeSelect.loc[sizeSelect['shoeCondition'] == category1]['price'].sort_values().iloc[0]
                price2 = sizeSelect.loc[sizeSelect['shoeCondition'] == category2]['price'].sort_values().iloc[0]
            #box exists in good condition
            elif boxCond == 1:
                price1 = sizeSelect.loc[sizeSelect['shoeCondition'] == category1]
                if 'good_condition' not in price1['boxCondition'].values:
                    continue
                price2 = sizeSelect.loc[sizeSelect['shoeCondition'] == category2]
                if 'good_condition' not in price2['boxCondition'].values:
                    continue
                price1 = price1.loc[sizeSelect['boxCondition'] == 'good_condition']['price']
                price2 = price2.loc[sizeSelect['boxCondition'] == 'good_condition']['price']
            #box exists
            elif boxCond == 2:
                price1 = sizeSelect.loc[sizeSelect['shoeCondition'] == category1]
                if (('good_condition' not in price1['boxCondition'].values) 
                    and ('badly_damaged' not in price1['boxCondition'].values)
                    and ('missing_lid' not in price1['boxCondition'].values)):
                    continue
                price2 = sizeSelect.loc[sizeSelect['shoeCondition'] == category2]
                if (('good_condition' not in price2['boxCondition'].values)
                    and ('badly_damaged' not in price2['boxCondition'].values)
                    and ('missing_lid' not in price2['boxCondition'].values)):
                    continue
                price1 = price1['price'].sort_values().iloc[0]
                price2 = price2['price'].sort_values().iloc[0]
            output[price1 - price2] = name, str(size)
    return output
            


#sortType 0 = used vs newNoDefect; 1 = newNoDefect vs newWithDefect; 2 = newNoDefectGoodBox vs newNoDefectBadBox
#boxCond 0 = no preference; 1 = box exists in good condition; 2 = box exists
priceChart = sizeSort(shoeDict["Air Jordan 1 Retro High OG 'Crimson Tint'"], sortType=1, boxCond=0, name="Air Jordan 1 Retro High OG 'Crimson Tint'")
bestDifference = np.max(list(priceChart.keys()))
print(bestDifference, priceChart[bestDifference])

27 ("Air Jordan 1 Retro High OG 'Crimson Tint'", '7.5')

In [123]:
for name, df in shoeDict.items():
    priceChart = sizeSort(df, sortType=1, boxCond=0, name=name)
    if len(priceChart) == 0:
        continue
    bestDifference = np.max(list(priceChart.keys()))

    print(bestDifference, priceChart[bestDifference])

12 ("Air Jordan 1 Retro High co.JP 'Midnight Navy' 2020", '13.0')
8 ("Air Jordan 1 Retro High OG 'Dark Mocha'", '10.5')
10 ("Air Jordan 11 Retro '25th Anniversary'", '9.5')
13 ("Air Jordan 5 Retro SE 'What The'", '14.0')
41 ("Air Jordan 1 Retro High OG 'Obsidian'", '9.0')
10 ("Sacai x VaporWaffle 'Black White'", '9.5')
19 ("Off-White x Air Jordan 5 SP 'Sail'", '8.5')
36 ("Air Jordan 1 Retro High OG 'Royal Toe'", '14.0')
1 ("Dunk Low SP Retro 'Ceramic' 2020", '10.0')
26 ("Air Jordan 4 Retro OG 'Fire Red' 2020", '12.0')
-58 ("Sacai x VaporWaffle 'Sail'", '10.5')
35 ("Air Jordan 1 Retro High OG 'Turbo Green'", '9.5')
33 ("Dunk Low SP Retro 'Veneer' 2020", '5.5')
1 ("Air Jordan 1 Mid 'Chicago Black Toe'", '10.0')
10 ("Yeezy 700 V3 'Safflower'", '8.0')
816 ("Off-White x Wmns Air Jordan 4 SP 'Sail'", '14.5')
140 ("Air Jordan 1 Retro High OG 'Court Purple 2.0'", '5.5')
5 ("Yeezy Boost 380 'Calcite Glow'", '12.5')
10 ("Air Jordan 1 Retro High co.JP GS 'Midnight Navy' 2020", '6.0')
15 ("Yeezy Boost 350 V2 'Carbon'", '8.0')
-13 ("Air Jordan 1 Retro High OG GS 'Dark Mocha'", '5.0')
4 ("Air Jordan 1 Mid 'Banned'", '11.0')
31 ("Air Jordan 4 Retro OG 'Bred' 2019", '10.0')
75 ("Air Jordan 11 Retro 'Bred' 2019", '12.0')
12 ("Air Jordan 1 Retro High 'Tokyo Bio Hack'", '7.5')
10 ("Air Jordan 1 Retro High OG 'Smoke Grey'", '11.0')
35 ("Air Jordan 1 Retro High OG 'Bloodline'", '11.5')
27 ("Air Jordan 1 Retro High OG 'Crimson Tint'", '7.5')
29 ("Air Jordan 12 Retro 'Dark Concord'", '7.5')
70 ("Yeezy Boost 350 V2 'Zebra'", '11.0')
88 ("Air Jordan 1 Retro High OG 'Pine Green 2.0'", '9.0')
25 ("Air Max 90 'Infrared' 2020", '8.0')
92 ("Air Jordan 4 Retro 'Black Cat' 2020", '7.0')
29 ("Yeezy Boost 350 V2 'Natural'", '8.0')
-4 ("Air Jordan 1 Retro High OG 'Shattered Backboard 3.0'", '8.0')
-1 ("Wmns Air Jordan 1 Retro High OG 'Lucky Green'", '12.0')
20 ("Union LA x Air Jordan 4 Retro 'Off Noir'", '10.0')
226 ("Travis Scott x Air Jordan 1 Retro High OG 'Mocha'", '13.0')
29 ("Air Force 1 '07 'White'", '7.0')
30 ("Air Jordan 6 Retro 'Infrared' 2019", '10.0')
117 ("Wmns Air Jordan 1 Retro High OG 'Blue Chill'", '7.0')
106 ("Dunk Low Pro SB 'Atmos Elephant'", '11.5')
70 ("Air Jordan 4 Retro 'Purple Metallic'", '12.5')
19 ("Off-White x Air Rubber Dunk 'Green Strike'", '5.0')
250 ("Yeezy Boost 350 V2 'Cream White / Triple White'", '16.0')

In [92]:
len(shoeDict)

50

In [114]:
list(shoeDict["Air Jordan 5 Retro SE 'What The'"]['price'])

[259,
 245,
 259,
 260,
 250,
 220,
 262,
 250,
 275,
 260,
 435,
 265,
 268,
 352,
 270,
 260,
 254,
 210,
 259,
 279,
 258,
 999,
 261,
 281,
 257,
 254,
 2000,
 282,
 264,
 269,
 800,
 255,
 300,
 261,
 271,
 310,
 450,
 270,
 290,
 269,
 263,
 265,
 263,
 276,
 334,
 280,
 269,
 310,
 279,
 285,
 315,
 283,
 350,
 269,
 280,
 279,
 277]